name: Build and Push Docker Image

on:
  schedule:
    - cron: '23 01 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      DATE_YYMMDD: ${{ format('{0:YY}{0:MM}{0:DD}', utcNow()) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/vsix-frr:${{ env.DATE_YYMMDD }}
          ghcr.io/${{ github.repository_owner }}/your_image_name:latest
